package main

type StateName string

const (
	Alabama       StateName = "AL"
	Alaska        StateName = "AK"
	Arizona       StateName = "AZ"
	Arkansas      StateName = "AR"
	California    StateName = "CA"
	Colorado      StateName = "CO"
	Connecticut   StateName = "CT"
	Delaware      StateName = "DE"
	Florida       StateName = "FL"
	Georgia       StateName = "GA"
	Hawaii        StateName = "HI"
	Idaho         StateName = "ID"
	Illinois      StateName = "IL"
	Indiana       StateName = "IN"
	Iowa          StateName = "IA"
	Kansas        StateName = "KS"
	Kentucky      StateName = "KY"
	Louisiana     StateName = "LA"
	Maine         StateName = "ME"
	Maryland      StateName = "MD"
	Massachusetts StateName = "MA"
	Michigan      StateName = "MI"
	Minnesota     StateName = "MN"
	Mississippi   StateName = "MS"
	Missouri      StateName = "MO"
	Montana       StateName = "MT"
	Nebraska      StateName = "NE"
	Nevada        StateName = "NV"
	NewHampshire  StateName = "NH"
	NewJersey     StateName = "NJ"
	NewMexico     StateName = "NM"
	NewYork       StateName = "NY"
	NorthCarolina StateName = "NC"
	NorthDakota   StateName = "ND"
	Ohio          StateName = "OH"
	Oklahoma      StateName = "OK"
	Oregon        StateName = "OR"
	Pennsylvania  StateName = "PA"
	RhodeIsland   StateName = "RI"
	SouthCarolina StateName = "SC"
	SouthDakota   StateName = "SD"
	Tennessee     StateName = "TN"
	Texas         StateName = "TX"
	Utah          StateName = "UT"
	Vermont       StateName = "VT"
	Virginia      StateName = "VA"
	Washington    StateName = "WA"
	WestVirginia  StateName = "WV"
	Wisconsin     StateName = "WI"
	Wyoming       StateName = "WY"
)
